//
// Created by Helldembez on 19-10-2021.
//
#include <stdio.h>

#define ARRAY_LENGTH(array) (sizeof((array))/sizeof((array)[0]))

typedef struct {
    char *key;
    char *value;
} Map;

typedef struct {
    char *key;
    char **value;
    int size;
} MapList;

typedef struct {
    char *key;
    char *value;
    Map *valueMapping;
    int vmSize;
    char *descText;
} CVARMapping;

static Map booleanInverse[] = {{"0", "1"},
                               {"1", "0"}};
static Map depthBitsValueMapping[] = {{"*", "24"}};
static Map tracerValueMapping[] = {{"2", "3"}};
static Map crosshairValueMapping[] = {{"1", "2"}};
static Map fontscaleValueMapping[] = {{"*", "0.22"}};

// Key must be lowercase because I dont want to perform tolower on it.
static CVARMapping cvarMapping[] =
        {
                {"cg_novoicechats",        "cg_voiceChats", .valueMapping = booleanInverse, .vmSize = 2},
                {"cg_novoicetext",         "cg_voiceText", .valueMapping =  booleanInverse, .vmSize = 2},

                {"debug_protocol",              NULL},
                {"debuggraph",                  NULL},
                {"devdll",                      NULL},
                {"dmflags",                     NULL},
                {"fraglimit",                   NULL},

                {"fs_buildgame",                NULL},
                {"fs_buildpath",                NULL},
                {"fs_cdpath",                   NULL},
                {"fs_copyfiles",                NULL},
                {"fs_restrict",                 NULL},

                {"headmodel",                   NULL},

                {"in_debugjoystick",            NULL},
                {"in_joyballscale",             NULL},
                {"in_midi",                     NULL},
                {"in_midichannel",              NULL},
                {"in_mididevice",               NULL},
                {"in_midiport",                 NULL},

                {"joy_threshold",               NULL},

                {"mp_currentplayertype",        NULL},
                {"mp_currentteam",              NULL},
                {"mp_playertype",               NULL},
                {"mp_team",                     NULL},
                {"mp_weapon",                   NULL},

                {"net_noipx",                   NULL},
                {"net_noudp",                   NULL},

                {"r_depthbits",            "r_depthbits", .valueMapping = depthBitsValueMapping, .vmSize = 1},

                {"savegame_loading",            NULL},
                {"scr_conspeed",                NULL},
                {"server_autoconfig",           NULL},

                {"sys_cpuid",                   NULL},
                {"sys_cpustring",               NULL},

                {"team_maxpanzers",             NULL},

                {"vid_xpos",                    NULL},
                {"vid_ypos",                    NULL},

                {"win_hinstance",               NULL},
                {"win_wndproc",                 NULL},

                // etpro values mapping
                {"b_althud",               "cg_althud"},
                {"b_althudflags",          "cg_althudflags"},
                {"b_antilag",              "cg_antilag"},
                {"b_chatalpha",            "cg_chatbackgroundalpha"},
                {"b_chatflags",            "cg_chatflags"},
                {"b_drawclock",            "cg_drawTime"},
                {"b_drawfps",              "cg_drawfps"},
                {"b_drawranks",            "cg_drawCrosshairInfo", .valueMapping = crosshairValueMapping, .vmSize = 1},
                {"b_drawspeed",            "cg_drawspeed"},
                {"b_fireteamlatchedclass", "cg_fireteamlatchedclass"},
                {"b_hitsounds",            "cg_hitsounds"},
                {"b_locationjustify",      "cg_fireteamLocationAlign"},
                {"b_locationmaxchars",     "cg_locationmaxchars"},
                {"b_mapzoom",              "cg_automapzoom"},
                {"b_muzzleflash",          "cg_muzzleflash"},
                {"b_numpopups",            "cg_numpopups"},
                {"b_noactivatelean",       "cl_activatelean", .valueMapping = booleanInverse, .vmSize = 2},
                {"b_optimizeprediction",   "cg_optimizeprediction"},
                {"b_popupfadetime",        "cg_popupfadetime"},
                {"b_popupstaytime",        "cg_popupstaytime"},
                {"b_popuptime",            "cg_popuptime"},
                {"b_predefineddemokeys",   "cg_predefineddemokeys"},
                {"b_simpleitems",          "cg_simpleitems"},
                {"b_smallpopups",          "cg_drawsmallpopupicons"},
                {"b_tracers",              "cg_tracers", .valueMapping = tracerValueMapping, .vmSize = 1},
                {"b_votetextscale",        "cg_fontscalesp", .valueMapping = fontscaleValueMapping, .vmSize = 1, .descText = "This CVAR does not map 1 to 1. In legacy there are multiple font scaling cvars. Default is 0.22. See https://etlegacy.readthedocs.io/en/latest/cvars.html?highlight=fireteam#cg-fontscalesp-cvar-added"},
                {"b_weapaltreloads",       "cg_weapaltreloads"},

                // deleted etpro values
                {"b_backupcvars",               NULL},
                {"b_centeredweapons",           NULL},
                {"b_chatsounds",                NULL},
                {"b_cmdwarnings",               NULL},
                {"b_debugfakebmodel",           NULL},
                {"b_debuglocations",            NULL},
                {"b_debugsnapents",             NULL},
                {"b_demo_autotimescale",        NULL},
                {"b_demo_autotimescaleweapons", NULL},
                {"b_demo_dynamitecam",          NULL},
                {"b_demo_dynamitecounter",      NULL},
                {"b_demo_followxdistance",      NULL},
                {"b_demo_followydistance",      NULL},
                {"b_demo_followzdistance",      NULL},
                {"b_demo_freecamspeed",         NULL},
                {"b_demo_grenadecam",           NULL},
                {"b_demo_lookat",               NULL},
                {"b_demo_mortarcam",            NULL},
                {"b_demo_nametags",             NULL},
                {"b_demo_nopitch",              NULL},
                {"b_demo_panzercam",            NULL},
                {"b_demo_pitchturnspeed",       NULL},
                {"b_demo_playersprites",        NULL},
                {"b_demo_pvshint",              NULL},
                {"b_demo_rollspeed",            NULL},
                {"b_demo_teamonlymissilecam",   NULL},
                {"b_demo_yawturnspeed",         NULL},
                {"b_demorecord_statusline",     NULL},
                {"b_descriptivetextscale",      NULL},
                {"b_drawpromotions",            NULL},
                {"b_drawrewards",               NULL},
                {"b_drawspectatoralpha",        NULL},
                {"b_drawspectatorteamflags",    NULL},
                {"b_fireteamalpha",             NULL},
                {"b_fixedphysics",              NULL},
                {"b_goatsound",                 NULL},
                {"b_hudyoffset",                NULL},
                {"b_killshot_delay",            NULL},
                {"b_lagometeralpha",            NULL},
                {"b_locationmode",              NULL},
                {"b_logbanners",                NULL},
                {"b_panzerhack",                NULL},
                {"b_shovesounds",               NULL},
                {"b_speedinterval",             NULL},
                {"b_speedunit",                 NULL},
                {"b_textcolorfilter",           NULL},
                {"b_tjg_ghostfx",               NULL},
                {"b_tjl_color",                 NULL},
                {"b_tjl_draw",                  NULL},
                {"b_tjl_quickslot",             NULL},
                {"b_tjl_showmaxspeed",          NULL},
                {"b_tjl_stepsize",              NULL},
                {"b_tjl_stoponnomove",          NULL},
                {"b_watermarkalpha",            NULL},

                {"ui_*",                        NULL},
                {"b_*",                         NULL},
                {"g_*",                         NULL},
                {"vote_*",                      NULL},
                {"etj_*",                       NULL},
                {"tj_*",                        NULL},
                {"team_*",                      NULL},
                {"match_*",                     NULL},
                {"sv_*",                        NULL},
                {"hud_*",                       NULL},
                {"lua_*",                       NULL},
                {"omnibot_*",                   NULL},
                {"server_*",                    NULL},
                {"vm_*",                        NULL},
                {"bot_*",                       NULL},
                {"movie_*",                     NULL},
        };

static char *conCvars[] =
        {
                "con_defaultHeight",
                "con_autoclear",
                "con_openspeed",
                "con_notifytime",
                "con_numNotifies",
                "con_drawnotify",
                "con_background"
        };

static char *soundCvars[] =
        {
                "s_currentMusic",
                "s_device",
                "s_sdlMixSamps",
                "s_sdlDevSamps",
                "s_channels",
                "s_bits",
                "s_debugStreams",
                "s_testsound",
                "s_show",
                "s_mixOffset",
                "s_backend",
                "s_muted",
                "s_mixahead",
                "s_doppler",
                "s_mixPreStep",
                "s_muteWhenUnfocused",
                "s_muteWhenMinimized",
                "s_musicvolume",
                "s_volume",
                "s_initsound",
                "s_sdlLevelSamps",
                "s_khz"
        };

static char *cgCvars[] =
        {
                "cg_ui_voteFlags",
                "cg_spawnTimer_period",
                "cg_spawnTimer_set",
                "cg_etVersion",
                "cg_debugSkills",
                "cg_uinfo",
                "cg_stats",
                "cg_thirdPerson",
                "cg_thirdPersonAngle",
                "cg_thirdPersonRange",
                "cg_tracerlength",
                "cg_tracerSpeed",
                "cg_tracerwidth",
                "cg_tracerchance",
                "cg_showmiss",
                "cg_noplayeranims",
                "cg_nopredict",
                "cg_debugBullets",
                "cg_debugevents",
                "cg_debugposition",
                "cg_debuganim",
                "cg_animspeed",
                "cg_messageType",
                "cg_swingSpeed",
                "cg_gunZ",
                "cg_gunY",
                "cg_gunX",
                "cg_letterbox",
                "cg_recoilPitch",
                "cg_shovesounds",
                "cg_announcer",
                "cg_voiceChats",
                "cg_hitsounds",
                "cg_drawCompassIcons",
                "cg_drawEnvAwareness",
                "cg_fontscalesp",
                "cg_simpleItems",
                "cg_predefineddemokeys",
                "cg_popupstaytime",
                "cg_popupfadetime",
                "cg_optimizeprediction",
                "cg_automapzoom",
                "cg_locationmaxchars",
                "cg_fireteamLocationAlign",
                "cg_goatsound",
                "cg_fireteamlatchedclass",
                "cg_drawspeed",
                "cg_drawTime",
                "cg_chatflags",
                "cg_chatalpha",
                "cg_antilag",
                "cg_althudflags",
                "cg_altHud",
                "cg_tracers",
                "cg_gun_frame",
                "cg_weaponCycleDelay",
                "cg_teamChatTime",
                "cg_teamChatsOnly",
                "cg_teamChatHeight",
                "cg_specHelp",
                "cg_railTrailTime",
                "cg_lagometer",
                "cg_instanttapout",
                "cg_gibs",
                "cg_errordecay",
                "cg_drawWeaponIconFlash",
                "cg_drawStatus",
                "cg_drawSpreadScale",
                "cg_drawSnapshot",
                "cg_drawSmallPopupIcons",
                "cg_drawRoundTimer",
                "cg_drawReinforcementTime",
                "cg_drawFPS",
                "cg_drawFireteamOverlay",
                "cg_drawBuddies",
                "cg_draw2D",
                "cg_cycleAllWeaps",
                "cg_crosshairY",
                "cg_crosshairX",
                "cg_crosshairPulse",
                "cg_crosshairHealth",
                "cg_coronas",
                "cg_bobbing",
                "cg_bloodTime",
                "cg_bloodDamageBlend",
                "cg_autoaction",
                "cg_atmosphericEffects",
                "cg_muzzleflash",
                "cg_voiceText",
                "cg_drawCompass",
                "cg_descriptiveText",
                "cg_skybox",
                "cg_allowGeoIP",
                "cg_locations",
                "cg_shoutcastGrenadeTrail",
                "cg_shoutcastDrawHealth",
                "cg_shoutcastTeamNameBlue",
                "cg_shoutcastTeamNameRed",
                "cg_shoutcastDrawTeamNames",
                "cg_shoutcastDrawPlayers",
                "cg_crosshairAlphaAlt",
                "cg_coronafardist",
                "cg_crosshairColorAlt",
                "cg_crosshairAlpha",
                "cg_crosshairColor",
                "cg_printObjectiveInfo",
                "cg_complaintPopUp",
                "cg_useWeapsForZoom",
                "cg_noAmmoAutoSwitch",
                "cg_sharetimerText",
                "cg_bloodFlash",
                "cg_showblood",
                "cg_selectedPlayerName",
                "cg_selectedPlayer",
                "cg_markTime",
                "cg_drawSpectatorNames",
                "cg_drawCrosshairPickups",
                "cg_drawCrosshairNames",
                "cg_drawCrosshairInfo",
                "cg_brassTime",
                "cg_shadows",
                "cg_weapaltSwitches",
                "cg_weapaltReloads",
                "cg_autoReload",
                "cg_autoactivate",
                "cg_predictItems",
                "cg_zoomStepSniper",
                "cg_zoomDefaultSniper",
                "cg_drawCrosshair",
                "cg_crosshairSize",
                "cg_voiceSpriteTime",
                "cg_cursorHints",
                "cg_drawGun",
                "cg_drawTeamOverlay",
                "cg_popupLimboMenu",
                "cg_quickMessageAlt",
                "cg_drawNotifyText",
                "cg_autoswitch",
                "cg_customFont1",
                "cg_customFont2",
                "cg_shoutcastDrawMinimap",
                "cg_weapAnims",
                "cg_fov",
                "cg_drawPing",
                "cg_centertime",
                "cg_dynamicIcons",
                "cg_dynamicIconsDistance",
                "cg_dynamicIconsSize",
                "cg_dynamicIconsMaxScale",
                "cg_dynamicIconsMinScale",
                "cg_teamChatMention",
                "cg_autoFolders",
                "cg_bloodFlashTime",
                "cg_logFile",
                "cg_countryflags",
                "cg_fireteamNameMaxChars",
                "cg_fireteamNameAlign",
                "cg_fireteamSprites",
                "cg_fireteamAlpha",
                "cg_fireteamBgAlpha",
                "cg_simpleItemsScale",
                "cg_popupTime",
                "cg_numPopups",
                "cg_popupFilter",
                "cg_popupBigFilter",
                "cg_graphicObituaries",
                "cg_popupShadow",
                "cg_fontScaleTP",
                "cg_fontScaleCP",
                "cg_fontScaleCN",
                "cg_scoreboard",
                "cg_quickchat",
                "cg_drawUnit",
                "cg_visualEffects",
                "cg_bannerTime",
                "cg_chatX",
                "cg_chatY",
                "cg_chatScale",
                "cg_chatBackgroundAlpha",
                "cg_chatShadow",
                "cg_chatLineWidth",
                "cg_activateLean",
                "cg_healthDynamicColor",
                "cg_drawBreathPuffs",
                "cg_drawSpawnpoints",
                "cg_scopedSensitivityScaler"
        };

static char *rendererCvars[] =
        {
                "r_stencilbits",
                "r_displayRefresh",
                "r_customaspect",
                "r_swapInterval",
                "r_noborder",
                "r_gfxinfo",
                "r_maxpolyverts",
                "r_maxpolys",
                "r_screenshotJpegQuality",
                "r_screenshotFormat",
                "r_noportals",
                "r_lockpvs",
                "r_drawBuffer",
                "r_offsetunits",
                "r_offsetfactor",
                "r_clear",
                "r_normallength",
                "r_shownormals",
                "r_showsky",
                "r_trisColor",
                "r_showtris",
                "r_nobind",
                "r_debugSurface",
                "r_logFile",
                "r_speeds",
                "r_showcluster",
                "r_novis",
                "r_nocull",
                "r_ignore",
                "r_drawentities",
                "r_norefresh",
                "r_lodscale",
                "r_measureOverdraw",
                "r_skipBackEnd",
                "r_flareFade",
                "r_flareSize",
                "r_portalOnly",
                "r_lightmap",
                "r_drawworld",
                "r_nocurves",
                "r_fbo",
                "r_bonesDebug",
                "r_cacheModels",
                "r_cacheShaders",
                "r_cache",
                "r_printShaders",
                "r_debugSort",
                "r_debuglight",
                "r_showImages",
                "r_directedScale",
                "r_ambientScale",
                "r_railSegmentLength",
                "r_railWidth",
                "r_facePlaneCull",
                "r_finish",
                "r_drawSun",
                "r_ignoreGLErrors",
                "r_zfar",
                "r_znear",
                "r_lodCurveError",
                "r_singleShader",
                "r_greyscale",
                "r_subdivisions",
                "r_uifullscreen",
                "r_simpleMipMaps",
                "r_colorMipLevels",
                "r_roundImagesDown",
                "r_ext_max_anisotropy",
                "r_ext_texture_env_add",
                "r_ext_multitexture",
                "r_allowExtensions",
                "r_lodbias",
                "r_dynamicTextures",
                "r_fullscreen",
                "r_mode",
                "r_centerwindow",
                "r_ext_multisample",
                "r_ext_compressed_textures",
                "r_ext_texture_filter_anisotropic",
                "r_ignorehwgamma",
                "r_overBrightBits",
                "r_allowsoftwareGL",
                "r_intensity",
                "r_drawfoliage",
                "r_oldMode",
                "r_oldFullscreen",
                "r_windowLocation",
                "r_customheight",
                "r_customwidth",
                "r_allowResize",
                "r_scale",
                "r_wolffog",
                "r_textureMode",
                "r_dynamiclight",
                "r_flares",
                "r_ignoreFastPath",
                "r_picmip",
                "r_gamma",
                "r_fastsky",
                "r_detailtextures",
                "r_mapoverbrightbits",
                "r_colorbits",
                "r_depthbits",
                "r_texturebits"
        };

static char *comCvars[] =
        {
                "com_errorDiagnoseIP",
                "com_missingFiles",
                "com_updatefiles",
                "com_updateavailable",
                "com_updatemessage",
                "com_motdString",
                "com_motd",
                "com_minimized",
                "com_unfocused",
                "com_buildScript",
                "com_speeds",
                "com_showtrace",
                "com_hunkused",
                "com_soundMegs",
                "com_recommendedSet",
                "com_introplayed",
                "com_maxfps",
                "com_hunkMegs",
                "com_pidfile",
                "com_pid",
                "com_crashed",
                "com_ignorecrash",
                "com_ansiColor",
                "com_zoneMegs"
        };

static char *clientCvars[] =
        {
                "cl_downloadName",
                "cl_cacheGathering",
                "cl_maxRewindBackups",
                "cl_packetdelay",
                "cl_packetloss",
                "cl_waveoffset",
                "cl_wavefilename",
                "cl_waverecording",
                "cl_demooffset",
                "cl_demofilename",
                "cl_demorecording",
                "cl_bypassMouseInput",
                "cl_serverStatusResendTime",
                "cl_conXOffset",
                "cl_showmouserate",
                "cl_anglespeedkey",
                "cl_avimotionjpeg",
                "cl_forceavidemo",
                "cl_avidemo",
                "cl_autorecord",
                "cl_showTimeDelta",
                "cl_showSend",
                "cl_showServerCommands",
                "cl_shownuments",
                "cl_shownet",
                "cl_wavefilerecord",
                "cl_timeout",
                "cl_noprint",
                "cl_debugMove",
                "cl_nodelta",
                "cl_freezeDemo",
                "cl_paused",
                "cl_wwwDownload",
                "cl_run",
                "cl_packetdup",
                "cl_maxPing",
                "cl_freelook",
                "cl_doubletapdelay",
                "cl_allowDownload",
                "cl_mouseaccel",
                "cl_activatelean",
                "cl_yawspeed",
                "cl_timeNudge",
                "cl_pitchspeed",
                "cl_langDebug",
                "cl_lang",
                "cl_consoleKeys",
                "cl_maxpackets",
                "cl_avidemotype",
                "cl_extrapolationMargin",
                "cl_renderer",
                "cl_profile",
                "cl_defaultProfile"
        };

static MapList existingCvars[] =
        {
                {"con_*", conCvars,      ARRAY_LENGTH(conCvars)},
                {"s_*",   soundCvars,    ARRAY_LENGTH(soundCvars)},
                {"cg_*",  cgCvars,       ARRAY_LENGTH(cgCvars)},
                {"r_*",   rendererCvars, ARRAY_LENGTH(rendererCvars)},
                {"com_*", comCvars,      ARRAY_LENGTH(comCvars)},
                {"cl_*",  clientCvars,   ARRAY_LENGTH(clientCvars)}
        };

static const unsigned int cvarMappingSize = sizeof(cvarMapping) / sizeof(cvarMapping[0]);
static const unsigned int existingCvarsSize = sizeof(existingCvars) / sizeof(existingCvars[0]);