//
// Created by Helldembez on 19-10-2021.
//
#include <stdio.h>

#define ARRAY_LENGTH(array) (sizeof((array))/sizeof((array)[0]))

typedef struct {
    char *key;
    char *value;
} Map;

typedef struct {
    char *key;
    char **value;
    int size;
} MapList;

typedef struct {
    char *key;
    char *value;
    Map *valueMapping;
    int vmSize;
    char *descText;
} CVARMapping;

static Map booleanInverse[] = {{"0", "1"},
                               {"1", "0"}};
static Map depthBitsValueMapping[] = {{"*", "24"}};
static Map tracerValueMapping[] = {{"2", "3"}};
static Map crosshairValueMapping[] = {{"1", "2"}};
static Map fontscaleValueMapping[] = {{"*", "0.22"}};

// Key must be lowercase because I dont want to perform tolower on it.
static CVARMapping cvarMapping[] =
        {
                {"cg_novoicechats",        "cg_voiceChats", .valueMapping = booleanInverse, .vmSize = 2},
                {"cg_novoicetext",         "cg_voiceText", .valueMapping =  booleanInverse, .vmSize = 2},

                {"resettimer",             "timerreset"},

                {"debug_protocol",              NULL},
                {"debuggraph",                  NULL},
                {"devdll",                      NULL},
                {"dmflags",                     NULL},
                {"fraglimit",                   NULL},

                {"fs_buildgame",                NULL},
                {"fs_buildpath",                NULL},
                {"fs_cdpath",                   NULL},
                {"fs_copyfiles",                NULL},
                {"fs_restrict",                 NULL},

                {"headmodel",                   NULL},

                {"in_debugjoystick",            NULL},
                {"in_joyballscale",             NULL},
                {"in_midi",                     NULL},
                {"in_midichannel",              NULL},
                {"in_mididevice",               NULL},
                {"in_midiport",                 NULL},

                {"joy_threshold",               NULL},

                {"mp_currentplayertype",        NULL},
                {"mp_currentteam",              NULL},
                {"mp_playertype",               NULL},
                {"mp_team",                     NULL},
                {"mp_weapon",                   NULL},

                {"net_noipx",                   NULL},
                {"net_noudp",                   NULL},

                {"r_depthbits",            "r_depthbits", .valueMapping = depthBitsValueMapping, .vmSize = 1},

                {"savegame_loading",            NULL},
                {"scr_conspeed",                NULL},
                {"server_autoconfig",           NULL},

                {"sys_cpuid",                   NULL},
                {"sys_cpustring",               NULL},

                {"vid_xpos",                    NULL},
                {"vid_ypos",                    NULL},

                {"win_hinstance",               NULL},
                {"win_wndproc",                 NULL},

                // etpro values mapping
                {"b_althud",               "cg_althud"},
                {"b_althudflags",          "cg_althudflags"},
                {"b_antilag",              "cg_antilag"},
                {"b_chatalpha",            "cg_chatbackgroundalpha"},
                {"b_chatflags",            "cg_chatflags"},
                {"b_drawclock",            "cg_drawTime"},
                {"b_drawfps",              "cg_drawfps"},
                {"b_drawranks",            "cg_drawCrosshairInfo", .valueMapping = crosshairValueMapping, .vmSize = 1},
                {"b_drawspeed",            "cg_drawspeed"},
                {"b_fireteamlatchedclass", "cg_fireteamlatchedclass"},
                {"b_hitsounds",            "cg_hitsounds"},
                {"b_locationjustify",      "cg_fireteamLocationAlign"},
                {"b_locationmaxchars",     "cg_locationmaxchars"},
                {"b_mapzoom",              "cg_automapzoom"},
                {"b_muzzleflash",          "cg_muzzleflash"},
                {"b_numpopups",            "cg_numpopups"},
                {"b_noactivatelean",       "cl_activatelean", .valueMapping = booleanInverse, .vmSize = 2},
                {"b_optimizeprediction",   "cg_optimizeprediction"},
                {"b_popupfadetime",        "cg_popupfadetime"},
                {"b_popupstaytime",        "cg_popupstaytime"},
                {"b_popuptime",            "cg_popuptime"},
                {"b_predefineddemokeys",   "cg_predefineddemokeys"},
                {"b_simpleitems",          "cg_simpleitems"},
                {"b_smallpopups",          "cg_drawsmallpopupicons"},
                {"b_tracers",              "cg_tracers", .valueMapping = tracerValueMapping, .vmSize = 1},
                {"b_votetextscale",        "cg_fontscalesp", .valueMapping = fontscaleValueMapping, .vmSize = 1, .descText = "This CVAR does not map 1 to 1. In legacy there are multiple font scaling cvars. Default is 0.22. See https://etlegacy.readthedocs.io/en/latest/cvars.html?highlight=fireteam#cg-fontscalesp-cvar-added"},
                {"b_weapaltreloads",       "cg_weapaltreloads"},

                // deleted etpro values
                {"b_backupcvars",               NULL},
                {"b_centeredweapons",           NULL},
                {"b_chatsounds",                NULL},
                {"b_cmdwarnings",               NULL},
                {"b_debugfakebmodel",           NULL},
                {"b_debuglocations",            NULL},
                {"b_debugsnapents",             NULL},
                {"b_demo_autotimescale",        NULL},
                {"b_demo_autotimescaleweapons", NULL},
                {"b_demo_dynamitecam",          NULL},
                {"b_demo_dynamitecounter",      NULL},
                {"b_demo_followxdistance",      NULL},
                {"b_demo_followydistance",      NULL},
                {"b_demo_followzdistance",      NULL},
                {"b_demo_freecamspeed",         NULL},
                {"b_demo_grenadecam",           NULL},
                {"b_demo_lookat",               NULL},
                {"b_demo_mortarcam",            NULL},
                {"b_demo_nametags",             NULL},
                {"b_demo_nopitch",              NULL},
                {"b_demo_panzercam",            NULL},
                {"b_demo_pitchturnspeed",       NULL},
                {"b_demo_playersprites",        NULL},
                {"b_demo_pvshint",              NULL},
                {"b_demo_rollspeed",            NULL},
                {"b_demo_teamonlymissilecam",   NULL},
                {"b_demo_yawturnspeed",         NULL},
                {"b_demorecord_statusline",     NULL},
                {"b_descriptivetextscale",      NULL},
                {"b_drawpromotions",            NULL},
                {"b_drawrewards",               NULL},
                {"b_drawspectatoralpha",        NULL},
                {"b_drawspectatorteamflags",    NULL},
                {"b_fireteamalpha",             NULL},
                {"b_fixedphysics",              NULL},
                {"b_goatsound",                 NULL},
                {"b_hudyoffset",                NULL},
                {"b_killshot_delay",            NULL},
                {"b_lagometeralpha",            NULL},
                {"b_locationmode",              NULL},
                {"b_logbanners",                NULL},
                {"b_panzerhack",                NULL},
                {"b_shovesounds",               NULL},
                {"b_speedinterval",             NULL},
                {"b_speedunit",                 NULL},
                {"b_textcolorfilter",           NULL},
                {"b_tjg_ghostfx",               NULL},
                {"b_tjl_color",                 NULL},
                {"b_tjl_draw",                  NULL},
                {"b_tjl_quickslot",             NULL},
                {"b_tjl_showmaxspeed",          NULL},
                {"b_tjl_stepsize",              NULL},
                {"b_tjl_stoponnomove",          NULL},
                {"b_watermarkalpha",            NULL},

                {"ui_*",                        NULL},
                {"b_*",                         NULL},
                {"g_*",                         NULL},
                {"vote_*",                      NULL},
                {"etj_*",                       NULL},
                {"tj_*",                        NULL},
                {"team_*",                      NULL},
                {"match_*",                     NULL},
                {"sv_*",                        NULL},
                {"hud_*",                       NULL},
                {"lua_*",                       NULL},
                {"omnibot_*",                   NULL},
                {"server_*",                    NULL},
                {"vm_*",                        NULL},
                {"bot_*",                       NULL},
                {"movie_*",                     NULL},
                {"image_*",                     NULL},
        };

static char *conCvars[] =
        {
                "con_defaultHeight",
                "con_autoclear",
                "con_openspeed",
                "con_notifytime",
                "con_numNotifies",
                "con_drawnotify",
                "con_background"
        };

static char *soundCvars[] =
        {
                "s_currentmusic",
                "s_device",
                "s_sdlmixsamps",
                "s_sdldevsamps",
                "s_channels",
                "s_bits",
                "s_debugstreams",
                "s_testsound",
                "s_show",
                "s_mixoffset",
                "s_backend",
                "s_muted",
                "s_mixahead",
                "s_doppler",
                "s_mixprestep",
                "s_mutewhenunfocused",
                "s_mutewhenminimized",
                "s_musicvolume",
                "s_volume",
                "s_initsound",
                "s_sdllevelsamps",
                "s_khz"
        };

static char *cgCvars[] =
        {
                "cg_ui_voteflags",
                "cg_spawntimer_period",
                "cg_spawntimer_set",
                "cg_etversion",
                "cg_debugskills",
                "cg_uinfo",
                "cg_stats",
                "cg_thirdperson",
                "cg_thirdpersonangle",
                "cg_thirdpersonrange",
                "cg_tracerlength",
                "cg_tracerspeed",
                "cg_tracerwidth",
                "cg_tracerchance",
                "cg_showmiss",
                "cg_noplayeranims",
                "cg_nopredict",
                "cg_debugbullets",
                "cg_debugevents",
                "cg_debugposition",
                "cg_debuganim",
                "cg_animspeed",
                "cg_messagetype",
                "cg_swingspeed",
                "cg_gunz",
                "cg_guny",
                "cg_gunx",
                "cg_letterbox",
                "cg_recoilpitch",
                "cg_shovesounds",
                "cg_announcer",
                "cg_voicechats",
                "cg_hitsounds",
                "cg_drawcompassicons",
                "cg_drawenvawareness",
                "cg_fontscalesp",
                "cg_simpleitems",
                "cg_predefineddemokeys",
                "cg_popupstaytime",
                "cg_popupfadetime",
                "cg_optimizeprediction",
                "cg_automapzoom",
                "cg_locationmaxchars",
                "cg_fireteamlocationalign",
                "cg_goatsound",
                "cg_fireteamlatchedclass",
                "cg_drawspeed",
                "cg_drawtime",
                "cg_chatflags",
                "cg_chatalpha",
                "cg_antilag",
                "cg_althudflags",
                "cg_althud",
                "cg_tracers",
                "cg_gun_frame",
                "cg_weaponcycledelay",
                "cg_teamchattime",
                "cg_teamchatsonly",
                "cg_teamchatheight",
                "cg_spechelp",
                "cg_railtrailtime",
                "cg_lagometer",
                "cg_instanttapout",
                "cg_gibs",
                "cg_errordecay",
                "cg_drawweaponiconflash",
                "cg_drawstatus",
                "cg_drawspreadscale",
                "cg_drawsnapshot",
                "cg_drawsmallpopupicons",
                "cg_drawroundtimer",
                "cg_drawreinforcementtime",
                "cg_drawfps",
                "cg_drawfireteamoverlay",
                "cg_drawbuddies",
                "cg_draw2d",
                "cg_cycleallweaps",
                "cg_crosshairy",
                "cg_crosshairx",
                "cg_crosshairpulse",
                "cg_crosshairhealth",
                "cg_coronas",
                "cg_bobbing",
                "cg_bloodtime",
                "cg_blooddamageblend",
                "cg_autoaction",
                "cg_atmosphericeffects",
                "cg_muzzleflash",
                "cg_voicetext",
                "cg_drawcompass",
                "cg_descriptivetext",
                "cg_skybox",
                "cg_allowgeoip",
                "cg_locations",
                "cg_shoutcastgrenadetrail",
                "cg_shoutcastdrawhealth",
                "cg_shoutcastteamnameblue",
                "cg_shoutcastteamnamered",
                "cg_shoutcastdrawteamnames",
                "cg_shoutcastdrawplayers",
                "cg_crosshairalphaalt",
                "cg_coronafardist",
                "cg_crosshaircoloralt",
                "cg_crosshairalpha",
                "cg_crosshaircolor",
                "cg_printobjectiveinfo",
                "cg_complaintpopup",
                "cg_useweapsforzoom",
                "cg_noammoautoswitch",
                "cg_sharetimertext",
                "cg_bloodflash",
                "cg_showblood",
                "cg_selectedplayername",
                "cg_selectedplayer",
                "cg_marktime",
                "cg_drawspectatornames",
                "cg_drawcrosshairpickups",
                "cg_drawcrosshairnames",
                "cg_drawcrosshairinfo",
                "cg_brasstime",
                "cg_shadows",
                "cg_weapaltswitches",
                "cg_weapaltreloads",
                "cg_autoreload",
                "cg_autoactivate",
                "cg_predictitems",
                "cg_zoomstepsniper",
                "cg_zoomdefaultsniper",
                "cg_drawcrosshair",
                "cg_crosshairsize",
                "cg_voicespritetime",
                "cg_cursorhints",
                "cg_drawgun",
                "cg_drawteamoverlay",
                "cg_popuplimbomenu",
                "cg_quickmessagealt",
                "cg_drawnotifytext",
                "cg_autoswitch",
                "cg_customfont1",
                "cg_customfont2",
                "cg_shoutcastdrawminimap",
                "cg_weapanims",
                "cg_fov",
                "cg_drawping",
                "cg_centertime",
                "cg_dynamicicons",
                "cg_dynamiciconsdistance",
                "cg_dynamiciconssize",
                "cg_dynamiciconsmaxscale",
                "cg_dynamiciconsminscale",
                "cg_teamchatmention",
                "cg_autofolders",
                "cg_bloodflashtime",
                "cg_logfile",
                "cg_countryflags",
                "cg_fireteamnamemaxchars",
                "cg_fireteamnamealign",
                "cg_fireteamsprites",
                "cg_fireteamalpha",
                "cg_fireteambgalpha",
                "cg_simpleitemsscale",
                "cg_popuptime",
                "cg_numpopups",
                "cg_popupfilter",
                "cg_popupbigfilter",
                "cg_graphicobituaries",
                "cg_popupshadow",
                "cg_fontscaletp",
                "cg_fontscalecp",
                "cg_fontscalecn",
                "cg_scoreboard",
                "cg_quickchat",
                "cg_drawunit",
                "cg_visualeffects",
                "cg_bannertime",
                "cg_chatx",
                "cg_chaty",
                "cg_chatscale",
                "cg_chatbackgroundalpha",
                "cg_chatshadow",
                "cg_chatlinewidth",
                "cg_activatelean",
                "cg_healthdynamiccolor",
                "cg_drawbreathpuffs",
                "cg_drawspawnpoints",
                "cg_scopedsensitivityscaler"
        };

static char *rendererCvars[] =
        {
                "r_stencilbits",
                "r_displayrefresh",
                "r_customaspect",
                "r_swapinterval",
                "r_noborder",
                "r_gfxinfo",
                "r_maxpolyverts",
                "r_maxpolys",
                "r_screenshotjpegquality",
                "r_screenshotformat",
                "r_noportals",
                "r_lockpvs",
                "r_drawbuffer",
                "r_offsetunits",
                "r_offsetfactor",
                "r_clear",
                "r_normallength",
                "r_shownormals",
                "r_showsky",
                "r_triscolor",
                "r_showtris",
                "r_nobind",
                "r_debugsurface",
                "r_logfile",
                "r_speeds",
                "r_showcluster",
                "r_novis",
                "r_nocull",
                "r_ignore",
                "r_drawentities",
                "r_norefresh",
                "r_lodscale",
                "r_measureoverdraw",
                "r_skipbackend",
                "r_flarefade",
                "r_flaresize",
                "r_portalonly",
                "r_lightmap",
                "r_drawworld",
                "r_nocurves",
                "r_fbo",
                "r_bonesdebug",
                "r_cachemodels",
                "r_cacheshaders",
                "r_cache",
                "r_printshaders",
                "r_debugsort",
                "r_debuglight",
                "r_showimages",
                "r_directedscale",
                "r_ambientscale",
                "r_railsegmentlength",
                "r_railwidth",
                "r_faceplanecull",
                "r_finish",
                "r_drawsun",
                "r_ignoreglerrors",
                "r_zfar",
                "r_znear",
                "r_lodcurveerror",
                "r_singleshader",
                "r_greyscale",
                "r_subdivisions",
                "r_uifullscreen",
                "r_simplemipmaps",
                "r_colormiplevels",
                "r_roundimagesdown",
                "r_ext_max_anisotropy",
                "r_ext_texture_env_add",
                "r_ext_multitexture",
                "r_allowextensions",
                "r_lodbias",
                "r_dynamictextures",
                "r_fullscreen",
                "r_mode",
                "r_centerwindow",
                "r_ext_multisample",
                "r_ext_compressed_textures",
                "r_ext_texture_filter_anisotropic",
                "r_ignorehwgamma",
                "r_overbrightbits",
                "r_allowsoftwaregl",
                "r_intensity",
                "r_drawfoliage",
                "r_oldmode",
                "r_oldfullscreen",
                "r_windowlocation",
                "r_customheight",
                "r_customwidth",
                "r_allowresize",
                "r_scale",
                "r_wolffog",
                "r_texturemode",
                "r_dynamiclight",
                "r_flares",
                "r_ignorefastpath",
                "r_picmip",
                "r_gamma",
                "r_fastsky",
                "r_detailtextures",
                "r_mapoverbrightbits",
                "r_colorbits",
                "r_depthbits",
                "r_texturebits"
        };

static char *comCvars[] =
        {
                "com_errordiagnoseip",
                "com_missingfiles",
                "com_updatefiles",
                "com_updateavailable",
                "com_updatemessage",
                "com_motdstring",
                "com_motd",
                "com_minimized",
                "com_unfocused",
                "com_buildscript",
                "com_speeds",
                "com_showtrace",
                "com_hunkused",
                "com_soundmegs",
                "com_recommendedset",
                "com_introplayed",
                "com_maxfps",
                "com_hunkmegs",
                "com_pidfile",
                "com_pid",
                "com_crashed",
                "com_ignorecrash",
                "com_ansicolor",
                "com_zonemegs"
        };

static char *clientCvars[] =
        {
                "cl_downloadname",
                "cl_cachegathering",
                "cl_maxrewindbackups",
                "cl_packetdelay",
                "cl_packetloss",
                "cl_waveoffset",
                "cl_wavefilename",
                "cl_waverecording",
                "cl_demooffset",
                "cl_demofilename",
                "cl_demorecording",
                "cl_bypassmouseinput",
                "cl_serverstatusresendtime",
                "cl_conxoffset",
                "cl_showmouserate",
                "cl_anglespeedkey",
                "cl_avimotionjpeg",
                "cl_forceavidemo",
                "cl_avidemo",
                "cl_autorecord",
                "cl_showtimedelta",
                "cl_showsend",
                "cl_showservercommands",
                "cl_shownuments",
                "cl_shownet",
                "cl_wavefilerecord",
                "cl_timeout",
                "cl_noprint",
                "cl_debugmove",
                "cl_nodelta",
                "cl_freezedemo",
                "cl_paused",
                "cl_wwwdownload",
                "cl_run",
                "cl_packetdup",
                "cl_maxping",
                "cl_freelook",
                "cl_doubletapdelay",
                "cl_allowdownload",
                "cl_mouseaccel",
                "cl_activatelean",
                "cl_yawspeed",
                "cl_timenudge",
                "cl_pitchspeed",
                "cl_langdebug",
                "cl_lang",
                "cl_consolekeys",
                "cl_maxpackets",
                "cl_avidemotype",
                "cl_extrapolationmargin",
                "cl_renderer",
                "cl_profile",
                "cl_defaultprofile"
        };

static MapList existingCvars[] =
        {
                {"con_*", conCvars,      ARRAY_LENGTH(conCvars)},
                {"s_*",   soundCvars,    ARRAY_LENGTH(soundCvars)},
                {"cg_*",  cgCvars,       ARRAY_LENGTH(cgCvars)},
                {"r_*",   rendererCvars, ARRAY_LENGTH(rendererCvars)},
                {"com_*", comCvars,      ARRAY_LENGTH(comCvars)},
                {"cl_*",  clientCvars,   ARRAY_LENGTH(clientCvars)}
        };

static const unsigned int cvarMappingSize = sizeof(cvarMapping) / sizeof(cvarMapping[0]);
static const unsigned int existingCvarsSize = sizeof(existingCvars) / sizeof(existingCvars[0]);